/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TelasDiretor;

import Classes.Departamento;
import Classes.Empregado;
import Classes.Estagiario;
import Classes.Gerente;
import ClassesAux.Data;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Binho
 */
public class AttDep extends javax.swing.JFrame {

    /**
     * Creates new form AttDep
     */
    
    Departamento dep;
    List<Estagiario> listaEstagiarios = null;
    List<Empregado> listaEmpregado = null;
    List<Gerente> listaGerente = null;
    
    public AttDep() {
        initComponents();
    }
    
    public AttDep(Departamento dep) {
        initComponents();
        Gerente g = new Gerente(Gerente.buscarCod(listaGerente, dep.getGerenteResponsavel()));
        jLabel5.setText("Nome antigo do Departemanto: " + dep.getNome());
        jLabel1.setText("O atual gerente é " + g.getNome() + " do código: " + dep.getGerenteResponsavel());
        this.dep = dep;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Atualizar Departamento");

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jButton2.setText("Confirmar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Código do novo Gerente:");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("O atual gerente é Fulano do código X");

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jLabel4.setText("Novo nome do Departamento:");

        jLabel5.setText("Nome antigo do Departemanto:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 41, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(!jTextField3.getText().isEmpty() && jTextField1.getText().isEmpty()){
            dep.setNome(jTextField3.getText());
            //exclui departamento

            //grava departamento

            //sucesso
             JOptionPane.showMessageDialog(null, "Departament Atualizado!", "Departamento Atualizado", JOptionPane.INFORMATION_MESSAGE);
        } else if (jTextField3.getText().isEmpty() && !jTextField1.getText().isEmpty()){
            //att departamento
            Estagiario estagiario = new Estagiario(Estagiario.buscarDepartamentoPorCodigo(listaEstagiarios, Integer.parseInt(jTextField1.getText())));
            Empregado empregado = new Empregado(Empregado.buscarDepartamentoPorCodigo(listaEmpregado, Integer.parseInt(jTextField1.getText())));
            if (estagiario != null) {
                Gerente Ngerente = new Gerente(estagiario.getNome(), estagiario.getSenha(), estagiario.getIdade(), estagiario.getTelefone(), estagiario.getEmail(), estagiario.getCPF(), Data.getDataAtual(), estagiario.getDataN(), "Gerente", 0);
                Ngerente.setDepartamento(dep.getCodigo());
                //grava gerente 

                //troca gerente
                dep.setGerenteResponsavel(Ngerente.getCodigo());
                //exclui estagiario

                estagiario = null;
                //exclui departamento

                //grava departamento

                //sucesso
                JOptionPane.showMessageDialog(null, "Departament Atualizado!", "Departamento Atualizado", JOptionPane.INFORMATION_MESSAGE);
            }else if (empregado != null){
                Gerente Ngerente = new Gerente(empregado.getNome(), empregado.getSenha(),empregado.getIdade(), empregado.getTelefone(), empregado.getEmail(), empregado.getCPF(), Data.getDataAtual(), empregado.getDataN(), "Gerente", 0);
                Ngerente.setDepartamento(dep.getCodigo());
                //grava gerente 

                //troca gerente
                dep.setGerenteResponsavel(Ngerente.getCodigo());
                //exclui empregado

                empregado = null;
                //exclui departamento

                //grava departamento

                //sucesso
                JOptionPane.showMessageDialog(null, "Departament Criado!", "Departamento Atualizado", JOptionPane.INFORMATION_MESSAGE);
            }else if (empregado == null && estagiario == null){
                JOptionPane.showMessageDialog(null, "Escolha um empregado ou estagiário", "Error", JOptionPane.INFORMATION_MESSAGE);
            }
        } else if (!jTextField3.getText().isEmpty() && !jTextField1.getText().isEmpty()){
            //troca o nome
            dep.setNome(jTextField3.getText());
            //att departamento
            Estagiario estagiario = new Estagiario(Estagiario.buscarDepartamentoPorCodigo(listaEstagiarios, Integer.parseInt(jTextField1.getText())));
            Empregado empregado = new Empregado(Empregado.buscarDepartamentoPorCodigo(listaEmpregado, Integer.parseInt(jTextField1.getText())));
            if (estagiario != null) {
                Gerente Ngerente = new Gerente(estagiario.getNome(), estagiario.getSenha(), estagiario.getIdade(), estagiario.getTelefone(), estagiario.getEmail(), estagiario.getCPF(), Data.getDataAtual(), estagiario.getDataN(), "Gerente", 0);
                Ngerente.setDepartamento(dep.getCodigo());
                //grava gerente 

                //troca gerente
                dep.setGerenteResponsavel(Ngerente.getCodigo());
                //exclui estagiario

                estagiario = null;
                //exclui departamento

                //grava departamento

                //sucesso
                JOptionPane.showMessageDialog(null, "Departament Atualizado!", "Departamento Atualizado", JOptionPane.INFORMATION_MESSAGE);
            }else if (empregado != null){
                Gerente Ngerente = new Gerente(empregado.getNome(), empregado.getSenha(),empregado.getIdade(), empregado.getTelefone(), empregado.getEmail(), empregado.getCPF(), Data.getDataAtual(), empregado.getDataN(), "Gerente", 0);
                Ngerente.setDepartamento(dep.getCodigo());
                //grava gerente 

                //troca gerente
                dep.setGerenteResponsavel(Ngerente.getCodigo());
                //exclui empregado

                empregado = null;
                //exclui departamento

                //grava departamento

                //sucesso
                JOptionPane.showMessageDialog(null, "Departament Criado!", "Departamento Atualizado", JOptionPane.INFORMATION_MESSAGE);
            }else if (empregado == null && estagiario == null){
                JOptionPane.showMessageDialog(null, "Escolha um empregado ou estagiário", "Error", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AttDep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AttDep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AttDep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AttDep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AttDep().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private static javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private static javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
